# Generated by Django 2.1.2 on 2018-12-13 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(help_text='Enter Dog name', max_length=20, unique=True, verbose_name='Dog name')),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='Enter hotel name', max_length=40, unique=True, verbose_name='Hotel name')),
                ('room_text', models.CharField(help_text='Enter hotel name', max_length=40, unique=True, validators=[django.core.validators.MinValueValidator('0'), django.core.validators.MaxValueValidator('100')], verbose_name='Hotel name')),
                ('room_number', models.PositiveIntegerField(blank=True, default=0, help_text='Must be zero', null=True, verbose_name='User Count')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='User Rate')),
                ('dog_relate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Dog', verbose_name='Ethnic Food')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-hotel_name'],
            },
        ),
    ]
