# Generated by Django 2.1.2 on 2018-12-13 07:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='dog_relate_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Dog', verbose_name='Dog name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price >0'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_number',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Positive Integer', null=True, verbose_name='Room number'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_text',
            field=models.CharField(help_text='Enter Room name', max_length=40, unique=True, validators=[django.core.validators.MinValueValidator('\x00'), django.core.validators.MaxValueValidator('d')], verbose_name='Room name'),
        ),
    ]
