# Generated by Django 2.1.2 on 2018-12-13 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181213_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='room_text',
            field=models.TextField(help_text='Enter Room name', max_length=40, unique=True, validators=[django.core.validators.MinValueValidator('0'), django.core.validators.MaxValueValidator('100')], verbose_name='Room name'),
        ),
    ]
