# Generated by Django 2.1.2 on 2018-12-13 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20181213_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(help_text='Enter Cat', max_length=20, unique=True, verbose_name='Cat food')),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_text',
            field=models.TextField(help_text='Enter Room name', unique=True, validators=[django.core.validators.MinValueValidator('0'), django.core.validators.MaxValueValidator('100')], verbose_name='Room name'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cat_releate_name',
            field=models.ManyToManyField(to='application.Cat', verbose_name='Cat'),
        ),
    ]
