# Generated by Django 2.1.2 on 2018-12-13 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20181213_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='cat_releate_name',
            new_name='cat_relate_name',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='dog_relate_name',
            field=models.ForeignKey(help_text='Choose one', on_delete=django.db.models.deletion.CASCADE, to='application.Dog', verbose_name='Dog name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive Integer', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_number',
            field=models.PositiveIntegerField(default=0, help_text='Positive Integer', null=True, verbose_name='Room number'),
        ),
    ]
